-- Tools to interact with the AST generated by the parser
local Lib = require("expressive/library")

---@class Ast
local Ast = {}
Lib.Ast = Ast

--- Walks an ast, going through every node and calling the callback at it.
---@param ast table<number, Node>
---@param callback fun(node: Node)
function Ast.walk(ast, callback)
	for k, v in ipairs(ast) do
		if getmetatable(v) == Lib.Parser.Node then
			---@type Node
			callback(v)
		end
	end
end

return Ast