name: Linter

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/expressive/runtime/extensions/**'
  pull_request:
    paths:
    - 'lua/**'
    - '!lua/expressive/runtime/extensions/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Download GluaFixer 1.18.2
      run: |
        curl -o glualint.zip -L https://github.com/FPtje/GLuaFixer/releases/download/1.18.2/glualint-1.18.2-linux.zip
        unzip glualint.zip

    # Don't need to remove extensions, because they have different file extensions, unlike E2 ones.

    - name: Lint Code
      run: ./glualint lua